### PR TITLE
fix: add import errors and warnings

### PR DESCRIPTION
**Pull request by marcelines**
## Description

Allow eslint to display errors about wrong imports.

### CODE REVIEW

**Review by danilowoz — COMMENTED** [review]
Missing dependency in the package.json

**Review by pbrandone — APPROVED** [review]
LGTM.

@danilowoz I assume the moduleDirectory array is correct?

@marcelines you are missing the import dependency

**Review by danilowoz — APPROVED** [review]
It seems the dependency is already in the package, great success!

**Review by pbrandone — CHANGES_REQUESTED** [review]
Missing dependency

**Review by pbrandone — APPROVED** [review]
Sorry :D I just saw @danilowoz's comments

**Pull request merged**
